[package]
name = "Seapad"
version = "1.0.0"
##new package
published-at = "0xeb76e5cbdb2850e37dd0a8f7f95ed6302ac632922ecca16cebd8e89d46b767a1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "1.0.1" }
Common = { local = "../common" }

[addresses]
##old package
seapad = "0x456ed33b6d806cd305f90f0d1fa395404880ba709c9c3218e7b826e514e3673f"
sui = "0x02"

##Test addresses
seedFund = "0x8880"
privateFund = "0x8881"
publicFund = "0x8882"
foundationFund = "0x8883"
advisorpartnerFund = "0x8884"
marketingFund = "0x8885"
ecosystemFund = "0x8886"
daoFund = "0x8887"