[package]
name = "Seapad"
version = "1.0.0"
##new package
published-at = "0x85cf6c9092f75772349ba593858986191bef9cf4da52629584458dc866956d2a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "1.0.1" }
Common = { local = "../common" }

[addresses]
##old package
seapad = "0x65fc5f6bd596258ba47ef6e65c52322623237b5e82cbef747b42c309d6ac704b"
sui = "0x02"

##Test addresses
seedFund = "0x8880"
privateFund = "0x8881"
publicFund = "0x8882"
foundationFund = "0x8883"
advisorpartnerFund = "0x8884"
marketingFund = "0x8885"
ecosystemFund = "0x8886"
daoFund = "0x8887"