[package]
name = "Common"
version = "0.0.1"
published-at = "0xc1f35d1803e705f821319bf0a71096af6ffb50bcabed3e395ce2b78412f93775"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "testnet" }

[addresses]
common =  "0xc1f35d1803e705f821319bf0a71096af6ffb50bcabed3e395ce2b78412f93775"
seapad = "0x00"
sui= "0x02"