[package]
name = "Common"
version = "1.0.0"
published-at = "0xd537ca3d976dde01617ecf4241c37b817038081928b7f922c4f13e3cb764f57c"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
W3libs = { git = "https://github.com/seapad-fund/w3libs", rev = "1.0.1"}

[addresses]
common =  "0xd537ca3d976dde01617ecf4241c37b817038081928b7f922c4f13e3cb764f57c"
sui= "0x02"