[package]
name = "Vesting"
version = "0.0.1"
#published-at=0x88682b28974ebfb3c6e1508982f0e8a2e8f4be48319e9d1eb3ba5c45a67ff800

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
seapad = "0x00"
sui = "0x02"

##test only
seedFund = "0x8880"
privateFund = "0x8881"
publicFund = "0x8882"
foundationFund = "0x8883"
advisorpartnerFund = "0x8884"
marketingFund = "0x8885"
ecosystemFund = "0x8886"
daoFund = "0x8887"