[package]
name = "Vesting"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
seapad = "0x00"
sui = "0x02"
ownerAdminCap= "0x7d0ad419e070245b777ec04461d02a6956afd2d19a3d8f96341dcf26f5053796"

##test only
seedFund = "0x8880"
privateFund = "0x8881"
publicFund = "0x8882"
foundationFund = "0x8883"
advisorpartnerFund = "0x8884"
marketingFund = "0x8885"
ecosystemFund = "0x8886"
daoFund = "0x8887"
