[package]
name = "StakeV2"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
seapad = "0x00"
sui = "0x02"