[package]
name = "SeapadNftWorkshop"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }

[addresses]
seapad="0x0"
sui="0x2"